#ifndef __RT_CONFIG_H__
#define __RT_CONFIG_H__

#include "cpu.h"

#define IDLE_THREAD_STACK_SIZE 4096

#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 100
#define RT_ALIGN_SIZE 4
#define RT_NAME_MAX 8
#define RT_MAIN_THREAD_STACK_SIZE 256
#define RT_USING_TIMER_SOFT 1
#define RT_TIMER_THREAD_PRIO 4
#define RT_TIMER_THREAD_STACK_SIZE 4096
#define RT_CONSOLEBUF_SIZE 256
#define RT_HEAP_SIZE (64 * 1024)
#define configSYSTICK_CLOCK_HZ (CPU_CLOCK_HZ)

#define RT_USING_USER_MAIN
#define RT_USING_IDLE_HOOK
#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE
#define RT_USING_MEMPOOL
#define RT_USING_HEAP
#define RT_USING_SMALL_MEM
#define RT_USING_TINY_SIZE
//#define RT_USING_CONSOLE

#endif /* __RT_CONFIG_H__ */
